[firefox] Add missing dep (#9083)
Attempting to fix broken build:
```
Step #3 - "compile-libfuzzer-address-x86_64": [34m 1:59.04(B[m /work/obj-fuzz/dist/bin/firefox -unittest --gtest_death_test_style=threadsafe(B[m(B[m
Step #3 - "compile-libfuzzer-address-x86_64": XPCOMGlueLoad error for file /work/obj-fuzz/dist/bin/libmozgtk.so:
Step #3 - "compile-libfuzzer-address-x86_64": libgtk-3.so.0: cannot open shared object file: No such file or directory
Step #3 - "compile-libfuzzer-address-x86_64": Couldn't load XPCOM.
Step #3 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Step #3 - "compile-libfuzzer-address-x86_64": Failed to build.
Step #3 - "compile-libfuzzer-address-x86_64": To reproduce, run:
Step #3 - "compile-libfuzzer-address-x86_64": python infra/helper.py build_image firefox
Step #3 - "compile-libfuzzer-address-x86_64": python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 firefox
Step #3 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Finished Step #3 - "compile-libfuzzer-address-x86_64"
ERROR
ERROR: build step 3 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```