fluxcd: Revert to base-builder-go to fix build (#8397)
fluxcd: Revert to base-builder-go
The project recently started moving into Go fuzz native, and using
the codeintelligencetesting variant is causing the error below:
ERROR: no interesting inputs were found

This PR reverts https://github.com/google/oss-fuzz/pull/7683 for fluxcd
which fixes the issue.

Signed-off-by: Paulo Gomes <pjbgf@linux.com>

Signed-off-by: Paulo Gomes <pjbgf@linux.com>