infra: print log data when Python fuzz_target fails (#12502)
## Description

This will make it easier to debug coverage failures that are not
reproducible locally.

The failure that I am trying to debug:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62231
-
https://oss-fuzz-build-logs.storage.googleapis.com/log-c420cf0c-f073-4c42-b75c-422971ef272e.txt

```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: Entering python fuzzing
Step #5: Error happened getting coverage of fuzz_parse
Step #5: This is likely because Atheris did not exit gracefully
```

Similar log data is displayed in other blocks:

https://github.com/google/oss-fuzz/blob/b094eca10f98215a08f549ef7963adca4d184998/infra/base-images/base-runner/coverage#L101-L105


https://github.com/google/oss-fuzz/blob/b094eca10f98215a08f549ef7963adca4d184998/infra/base-images/base-runner/coverage#L149-L153


https://github.com/google/oss-fuzz/blob/b094eca10f98215a08f549ef7963adca4d184998/infra/base-images/base-runner/coverage#L206-L210


https://github.com/google/oss-fuzz/blob/b094eca10f98215a08f549ef7963adca4d184998/infra/base-images/base-runner/coverage#L255-L260

---

This PR is a continuation of
https://github.com/google/oss-fuzz/pull/12405 with a renamed branch to
avoid trial-build errors:

```
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid build tag "testing-cm/display-coverage-log": must match format "^[\\w][\\w.-]{0,127}$"
```

Co-authored-by: Vitor Guidi <vitorguidi@gmail.com>