Remove fpizlo@apple.com from jsc
The user does not exist anymore.

HttpError: <HttpError 400 when requesting https://www.googleapis.com/storage/v1/b/jsc-quarantine.clusterfuzz-external.appspot.com/iam?alt=json returned "User fpizlo@apple.com does not exist.">