fix link failure with libtiff (#3050)
* fix link failure with libtiff

The fuzz targets were failing to link with:

```
Step #4: /work/lib/libtiff.a(tif_lzma.o): In function `TIFFInitLZMA':
Step #4: /src/libtiff/libtiff/tif_lzma.c:465: undefined reference to
`lzma_lzma_preset'
```

It looks like it's become necessary to explicitly link -llzma, see:

https://gitlab.com/libtiff/libtiff/commit/4159bda6db2f8cf8e848d8095b5d37d49ba67a10

oss-fuzz issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18928#c4

Thanks to @lovell.

* pin libtiff to 4.1.0

It seems there's an issue with git master libtiff -- it fails to link on
systems without lzma installed.

For now, pin to 4.1.0, the current stable version.

* explicitly disable lzma

lzma detection in libtiff seems to be broken as of 20 nov. Disable
explicitly.