libxslt: fix quote in project.yaml (#11596)
This was causing issues when parsing the `project.yaml` files:

```sh
  File "/home/dav/code/2024/fuzz-introspector-14/fuzz-introspector/tools/web-fuzzing-introspection/.venv/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/dav/code/2024/fuzz-introspector-14/fuzz-introspector/tools/web-fuzzing-introspection/.venv/lib/python3.10/site-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "<unicode string>", line 5, column 3:
      - "ddkilzer@apple.com"
      ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 15, column 6:
      - "albassam@apple.com"
         ^
```

fyi @oliverchang