libass: fix build, upgrade Ubuntu, update contacts (#6423)
* libass: update contact list

One contact is retired; another is currently inactive.

* libass: don't build HarfBuzz tests

They won't be used, so this just wastes resources.

* libass: upgrade to Ubuntu 20.04

The build failures on 20.04 were due to explicit listing
of static library dependencies, which have changed on 20.04:
png12 was replaced by png16, fontconfig was missing -luuid,
and png needed -lz to follow it, not precede.

Replace the explicit -l list by $(pkg-config --static --libs).
However, -lm must be filtered out as it causes linker errors:
  > undefined reference to `_dl_x86_cpu_features'

While we are at it, Ubuntu 20.04 comes with new-enough FriBidi,
so we can stop building it.

It also has new-enough HarfBuzz, but it depends on libgraphite2,
which lacks a static library in the system package, and dynamically
linking against a system library does not work in OSS-Fuzz
as the shared object will not exist in the run-time environment.

Reorder the dependencies alphabetically for consistency.